### ISSUE TITLE
Error when search for potential vulnerable web apps

### ISSUE THREAD

**Issue by PentesterTN** [S3cur3Th1sSh1t/WinPwn#26]
Hello,

Thank you for such great tool, I'm facing the below error everytime I choose the search for potential vulnerable web apps module:

================ WinPwn ================
Please choose wisely, master:: 12
invoke-expression : At line:1 char:34
+ cmd /c start powershell -Command {$Wcl = new-object System.Net.WebCli ...
+                                  ~
Missing closing '}' in statement block or type definition.
At line:1 char:25783
+ ... mRPbmx5LCAkVnVsbkxpbmtzDQogICAgICAgIH0NCiAgICB9DQp9")) | iex);$networ ...
+                                                                 ~
Unexpected token ')' in expression or statement.
At line:1 char:25968
+ ... ndColor Yellow 'Searching...';Find-Fruit -FoundOnly -Rhosts $network}
+                                                                         ~
Unexpected token '}' in expression or statement.
At C:\ProgramData\IMPACT\win2023\WinPwn-master\Offline_WinPwn.ps1:4325 char:5
+     invoke-expression 'cmd /c start powershell -Command {$Wcl = new-o ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : MissingEndCurlyBrace,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by S3cur3Th1sSh1t** [comment]
Hi,

looks like you are really going through all functions :bowtie:

Didn't use this one for a longer time. This was actually two "issues". One pipe broke the syntax in the Offline version and in both versions the script was caught by AMSI because it's loaded in a new PS process without bypassing AMSI before loading. 

So now with 3a1389a96c8af018b4645b571babab60691b66cf the script is loaded in the current process which solves both - but you have to wait the scan time now. 

Same "issue" currently applies to 'Inveigh' because it's also loaded in a new PS-process. I don't plan to "fix" the 'Inveigh' function atm so you need to use your own AMSI clean version here to get it working.

**Comment by PentesterTN** [comment]
hhh yes I really like the tool and I almost tried all the modules, fair enough thanks for the update, I will try it then I guess I will work on getting a clean version of it, much appreciated
